27 epic 2 issue 3 adding design to page
KC-LCW-Jan-23-Classroom/liftoff-theIncodables pull request #45
Opened 2023-10-20 17:03 UTC by cornballington

Moved styles to styles.css/

matched styles between login & registration forms/

added about us section to homepage

2023-10-20 17:31 UTC, Tam-Leonard approved these changes

2023-10-20 19:49 UTC, miserysauce commented on incodables-front-end/content-vibes-front-end/src/app/homepage/homepage.component.html
> +<div class="homepage-padding">
<!DOCTYPE html>
<html>

2023-10-20 19:52 UTC, miserysauce commented on incodables-front-end/content-vibes-front-end/src/app/homepage/homepage.component.html
> +
`</html>`

closing tag see above comment

2023-10-20 19:59 UTC, miserysauce requested changes
double check the tags, I might be wrong about the doctype and html tags but I wanted to address it before approving

2023-10-20 19:59 UTC, miserysauce commented on incodables-front-end/content-vibes-front-end/src/app/homepage/homepage.component.html
I think there still needs to be a `<!DOCTYPE html>` and an `<html>` tag.

2023-10-20 19:59 UTC, miserysauce commented on incodables-front-end/content-vibes-front-end/src/app/login/login.component.html
I think there still needs to be a `<!DOCTYPE html>` and an `<html>` tag.

2023-10-20 19:59 UTC, miserysauce commented on incodables-front-end/content-vibes-front-end/src/app/registration/registration.component.html
I think there still needs to be a `<!DOCTYPE html>` and an `<html>` tag.

2023-10-21 18:05 UTC, helhell01 commented on incodables-front-end/content-vibes-front-end/src/app/registration/registration.component.html
Nope, it's not actually required for component html pages since all of them are rendered inside the index.html file which includes all the <!DOCTYPE html> stuff

2023-10-21 18:28 UTC, miserysauce approved these changes

2023-10-21 18:28 UTC, merged